<?php
/**
 * Smart Digitech LLC (c) 2019, All right reverse
 * gci_clouds Project
 */

namespace app\api\modules;


use yii\filters\Cors;

/**
 * Class Module.php
 *
 * @author  Hung Dao <hungdao@dtsmart.vn>
 * * @package app\api\v1\report
 * * @version 1.0.0
 */
class Module extends \yii\base\Module
{
    /**
     * init
     * @author Binh Nguyen <binhnt@dtsmart.vn>
     */
    public function init()
    {
        parent::init();
        $this->modules = [
            'v1' => [
                'class' => \app\api\modules\v1\Module::class,
            ],
        ];
    }

    /**
     * behaviors
     * @return array
     * @author Binh Nguyen <binhnt@dtsmart.vn>
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub

        $behaviors['corsFilter'] = [
            'class' => Cors::class, // the new Cors class inherited from yii2's
            'cors' => [
                'Origin' => ['*'],
                'Access-Control-Request-Method' => ['GET', 'POST', 'OPTIONS'],
                'Access-Control-Request-Headers' => ['Origin', 'X-Requested-With', 'Content-Type', 'accept', 'Authorization', "UserIP"],
            ],
        ];
        return $behaviors;

    }

}