services:
  nginx-unit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_unit_app

    ports:
      - "8080:80"
      - "9001:9001"
    volumes:
      - .:/var/www/html
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    #    environment:
    #      - APP_ENV=production
    #      - YII_DEBUG=0
    #      - YII_ENV=prod
    networks:
      - app-network
    env_file:
      - app.env
volumes:
  db_data:

networks:
  app-network:


