<?php
/**
 * Smart Digitech LLC (c) 2019, All right reverse
 * gci_clouds Project
 */

namespace app\api\modules\v1\test;

/**
 * class Module.php
 *
 * @author  Binh Nguyen <binhnt@dtsmart.vn>
 * @package app\api\v1\airmessage
 * Date: 11/1/2022
 * Time: 1:02 AM
 * @version 1.0.0
 */
class Module extends \yii\base\Module
{
    /**
     * init
     * @author Binh Nguyen <binhnt@dtsmart.vn>
     */
    public function init()
    {
        parent::init();
    }

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}