<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\common\db\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\common\BusinessDataGoogleQuery;

/**
 * This is the base-model class for table "business_data_google".
 *
 * @property integer $id
 * @property integer $position
 * @property string $title
 * @property string $address
 * @property string $description
 * @property string $category
 * @property string $rating
 * @property string $place_id
 * @property double $latitude
 * @property double $longitude
 * @property string $country_code
 * @property string $main_image
 * @property string $check_store_place_id
 * @property string $time_update
 */
abstract class BusinessDataGoogle extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'business_data_google';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['position'], 'integer'],
            [['latitude', 'longitude'], 'number'],
            [['time_update'], 'safe'],
            [['title', 'address', 'description', 'category', 'rating', 'place_id', 'country_code', 'main_image', 'check_store_place_id'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'position' => 'Position',
            'title' => 'Title',
            'address' => 'Address',
            'description' => 'Description',
            'category' => 'Category',
            'rating' => 'Rating',
            'place_id' => 'Place ID',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
            'country_code' => 'Country Code',
            'main_image' => 'Main Image',
            'check_store_place_id' => 'Check Store Place ID',
            'time_update' => 'Time Update',
        ]);
    }

    /**
     * @inheritdoc
     * @return BusinessDataGoogleQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BusinessDataGoogleQuery(static::class);
    }
}
