<?php
/**
 * Smart Digitech LLC (c) 2019, All right reverse
 * GMV_Milano Project
 */

namespace app\api\modules\v1\report;

use yii\filters\auth\HttpBearerAuth;
use app\api\modules\v1\report\behaviors\Auth;

/**
 * class Module.php
 *
 * @author  Hung Dao <hungdao@dtsmart.vn>
 * @package app\api\v1\report
 * @version 1.0.0
 */
class Module extends \yii\base\Module
{
    /**
     * init
     * @author Hung Dao <hungdao@dtsmart.vn>
     */
    public function init()
    {
        parent::init();
    }

    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'bearerAuth' => [
                'class' => HttpBearerAuth::class,
                'user' => new Auth(),
            ],
        ]);
    }

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}